export const languages = new Map([
  ["English", "en"],
  ["Cebuano", "ceb"],
  ["German", "de"],
  ["French", "fr"],
  ["Swedish", "sv"],
  ["Dutch", "nl"],
  ["Russian", "ru"],
  ["Spanish", "es"],
  ["Italian", "it"],
  ["Polish", "pl"],
  ["Egyptian Arabic", "arz"],
  ["Chinese (writtenvernacular Chinese [en])", "zh"],
  ["Japanese", "ja"],
  ["Ukrainian", "uk"],
  ["Vietnamese", "vi"],
  ["Waray", "war"],
  ["Arabic", "ar"],
  ["Portuguese", "pt"],
  ["Persian", "fa"],
  ["Catalan", "ca"],
  ["Indonesian", "id"],
  ["Serbian", "sr"],
  ["Korean", "ko"],
  ["Norwegian (Bokmål)", "no"],
  ["Turkish", "tr"],
  ["Chechen", "ce"],
  ["Finnish", "fi"],
  ["Czech", "cs"],
  ["Hungarian", "hu"],
  ["Tatar", "tt"],
  ["Romanian", "ro"],
  ["Serbo-Croatian", "sh"],
  ["Basque", "eu"],
  ["Southern Min", "zh-min-nan"],
  ["Malay", "ms"],
  ["Hebrew", "he"],
  ["Esperanto", "eo"],
  ["Armenian", "hy"],
  ["Danish", "da"],
  ["Bulgarian", "bg"],
  ["Uzbek", "uz"],
  ["Welsh", "cy"],
  ["Simple English", "simple"],
  ["Slovak", "sk"],
  ["Estonian", "et"],
  ["Belarusian (officialNarkamaŭka [en] orthography)", "be"],
  ["South Azerbaijani", "azb"],
  ["Greek", "el"],
  ["Kazakh", "kk"],
  ["Minangkabau [en]", "min"],
  ["Croatian", "hr"],
  ["Lithuanian", "lt"],
  ["Galician", "gl"],
  ["Urdu", "ur"],
  ["Azerbaijani", "az"],
  ["Slovene", "sl"],
  ["Ladin", "lld"],
  ["Georgian", "ka"],
  ["Norwegian (Nynorsk)", "nn"],
  ["Tamil", "ta"],
  ["Thai", "th"],
  ["Hindi", "hi"],
  ["Bengali", "bn"],
  ["Macedonian", "mk"],
  ["Cantonese", "zh-yue"],
  ["Latin", "la"],
  ["Asturian", "ast"],
  ["Latvian", "lv"],
  ["Afrikaans", "af"],
  ["Tajik", "tg"],
  ["Burmese", "my"],
  ["Telugu", "te"],
  ["Albanian", "sq"],
  ["Malagasy", "mg"],
  ["Marathi", "mr"],
  ["Bosnian", "bs"],
  ["Occitan", "oc"],
  ["Belarusian(Taraškievica [en] orthography)", "be-tarask"],
  ["Breton", "br"],
  ["Malayalam", "ml"],
  ["Low German", "nds"],
  ["Swahili", "sw"],
  ["Kurdish (Kurmanji [en])", "ku"],
  ["Kyrgyz", "ky"],
  ["Lombard", "lmo"],
  ["Javanese", "jv"],
  ["Western Punjabi", "pnb"],
  ["Newar", "new"],
  ["Kurdish (Sorani)", "ckb"],
  ["Haitian Creole", "ht"],
  ["Venetian", "vec"],
  ["Piedmontese", "pms"],
  ["Luxembourgish", "lb"],
  ["Bashkir", "ba"],
  ["Sundanese", "su"],
  ["Irish", "ga"],
  ["Icelandic", "is"],
  ["Silesian", "szl"],
  ["Chuvash", "cv"],
  ["Punjabi", "pa"],
  ["West Frisian", "fy"],
  ["Ido", "io"],
  ["Hausa", "ha"],
  ["Tagalog", "tl"],
  ["Aragonese", "an"],
  ["Mazanderani", "mzn"],
  ["Wu Chinese", "wuu"],
  ["Zaza", "diq"],
  ["Volapük", "vo"],
  ["Igbo", "ig"],
  ["Scots", "sco"],
  ["Yoruba", "yo"],
  ["Kannada", "kn"],
  ["Nepali", "ne"],
  ["Alemannic German", "als"],
  ["Gujarati", "gu"],
  ["Interlingua", "ia"],
  ["Kotava", "avk"],
  ["Crimean Tatar", "crh"],
  ["Bavarian", "bar"],
  ["Sicilian", "scn"],
  ["Balinese", "ban"],
  ["Bishnupriya Manipuri [en]", "bpy"],
  ["Mongolian", "mn"],
  ["Quechua (Southern Quechua [en])", "qu"],
  ["Navajo", "nv"],
  ["Mingrelian", "xmf"],
  ["Sinhala", "si"],
  ["North Frisian", "frr"],
  ["Pashto", "ps"],
  ["Ossetian", "os"],
  ["Tumbuka [en]", "tum"],
  ["Odia", "or"],
  ["Sindhi", "sd"],
  ["Central Bikol [en]", "bcl"],
  ["Samogitian [en]", "bat-smg"],
  ["Yakut [en]", "sah"],
  ["Eastern Min [en]", "cdo"],
  ["Scottish Gaelic", "gd"],
  ["Buginese [en]", "bug"],
  ["Gilaki", "glk"],
  ["Yiddish", "yi"],
  ["Ilocano", "ilo"],
  ["Amharic", "am"],
  ["Limburgish", "li"],
  ["Neapolitan", "nap"],
  ["Gorontalo [en]", "gor"],
  ["Maithili", "mai"],
  ["Faroese", "fo"],
  ["Upper Sorbian", "hsb"],
  ["Banyumasan [en]", "map-bms"],
  ["Assamese", "as"],
  ["Shan [en]", "shn"],
  ["Classical Chinese", "zh-classical"],
  ["Emilian-Romagnol [en]", "eml"],
  ["Acehnese [en]", "ace"],
  ["Interlingue", "ie"],
  ["Walloon", "wa"],
  ["Sanskrit", "sa"],
  ["Western Armenian [en]", "hyw"],
  ["Santali", "sat"],
  ["Zulu", "zu"],
  ["Shona [en]", "sn"],
  ["Meadow Mari [en]", "mhr"],
  ["Ligurian", "lij"],
  ["Fiji Hindi", "hif"],
  ["Khmer", "km"],
  ["Banjarese [en]", "bjn"],
  ["Meitei", "mni"],
  ["Hill Mari [en]", "mrj"],
  ["Moroccan Arabic", "ary"],
  ["Hakka Chinese", "hak"],
  ["Dagbani [en]", "dag"],
  ["Kapampangan", "pam"],
  ["Tarantino [en]", "roa-tara"],
  ["Rusyn", "rue"],
  ["Bihari (Bhojpuri)", "bh"],
  ["Northern Sotho", "nso"],
  ["Corsican", "co"],
  ["Somali", "so"],
  ["Talysh [en]", "tly"],
  ["West Flemish [en]", "vls"],
  ["Māori", "mi"],
  ["Dutch Low Saxon", "nds-nl"],
  ["Northern Sámi", "se"],
  ["Erzya [en]", "myv"],
  ["Kinyarwanda", "rw"],
  ["Karakalpak [en]", "kaa"],
  ["Sardinian", "sc"],
  ["Central Tibetan [en] (Lhasa Tibetan [en])", "bo"],
  ["Cornish", "kw"],
  ["Veps [en]", "vep"],
  ["Turkmen", "tk"],
  ["Maltese", "mt"],
  ["Kabyle", "kab"],
  ["Manx", "gv"],
  ["Moksha [en]", "mdf"],
  ["Gan Chinese", "gan"],
  ["Võro", "fiu-vro"],
  ["Zeelandic", "zea"],
  ["Abkhaz", "ab"],
  ["Uyghur", "ug"],
  ["Saraiki", "skr"],
  ["Inari Sámi [en]", "smn"],
  ["Guarani", "gn"],
  ["Franco-Provençal", "frp"],
  ["Picard", "pcd"],
  ["Udmurt [en]", "udm"],
  ["Kashmiri", "ks"],
  ["Komi", "kv"],
  ["Kashubian", "csb"],
  ["Aymara", "ay"],
  ["Fula", "ff"],
  ["Norman", "nrm"],
  ["Old English", "ang"],
  ["Friulian", "fur"],
  ["Lingua Franca Nova", "lfn"],
  ["Livvi-Karelian [en]", "olo"],
  ["Lezgian", "lez"],
  ["Nahuatl", "nah"],
  ["Mirandese", "mwl"],
  ["Papiamento", "pap"],
  ["Twi [en]", "tw"],
  ["Saterland Frisian", "stq"],
  ["Lingala", "ln"],
  ["Lao", "lo"],
  ["Romansh", "rm"],
  ["Extremaduran", "ext"],
  ["Ladino", "lad"],
  ["Konkani (Goan Konkani)", "gom"],
  ["Doteli [en]", "dty"],
  ["Avar", "av"],
  ["Tuvan [en]", "tyv"],
  ["Komi-Permyak [en]", "koi"],
  ["Luganda", "lg"],
  ["Zamboanga Chavacano [en]", "cbk-zam"],
  ["Maldivian", "dv"],
  ["Ripuarian", "ksh"],
  ["Zhuang [en] (Standard Zhuang [en])", "za"],
  ["Buryat (Russia Buriat)", "bxr"],
  ["Pa'O [en]", "blk"],
  ["Gagauz", "gag"],
  ["Standard Moroccan Amazigh", "zgh"],
  ["Palatine German", "pfl"],
  ["Sakizaya [en]", "szy"],
  ["Betawi [en]", "bew"],
  ["Hawaiian", "haw"],
  ["Atayal [en]", "tay"],
  ["Pangasinan", "pag"],
  ["Pali", "pi"],
  ["Awadhi", "awa"],
  ["Tulu", "tcy"],
  ["Karachay-Balkar", "krc"],
  ["Ingush", "inh"],
  ["Xhosa", "xh"],
  ["Fon", "fon"],
  ["Atikamekw [en]", "atj"],
  ["Ghanaian Pidgin English [en]", "gpe"],
  ["Tongan", "to"],
  ["Pennsylvania Dutch", "pdc"],
  ["Mon", "mnw"],
  ["Aramaic (Syriac)", "arc"],
  ["Shilha", "shi"],
  ["Tswana", "tn"],
  ["Oromo [en]", "om"],
  ["Kikuyu [en]", "ki"],
  ["Kalmyk Oirat [en]", "xal"],
  ["Nias [en]", "nia"],
  ["Dagaare [en]", "dga"],
  ["Jamaican Patois", "jam"],
  ["Kabiye", "kbp"],
  ["Wolof", "wo"],
  ["Novial", "nov"],
  ["Kabardian", "kbd"],
  ["Angika [en]", "anp"],
  ["N'Ko [en]", "nqo"],
  ["Bislama", "bi"],
  ["Aromanian", "roa-rup"],
  ["Tok Pisin", "tpi"],
  ["Kongo", "kg"],
  ["Tetum", "tet"],
  ["Gun", "guw"],
  ["Lojban", "jbo"],
  ["Fijian", "fj"],
  ["Madurese [en]", "mad"],
  ["Lak", "lbe"],
  ["Tyap [en]", "kcg"],
  ["Nigerian Pidgin", "pcm"],
  ["Old Church Slavonic", "cu"],
  ["Tahitian", "ty"],
  ["Seediq [en]", "trv"],
  ["Samoan", "sm"],
  ["Amis [en]", "ami"],
  ["Dusun [en]", "dtp"],
  ["Sranan Tongo", "srn"],
  ["Mandailing Batak [en]", "btm"],
  ["Southern Altai [en]", "alt"],
  ["Latgalian [en]", "ltg"],
  ["French Guianese Creole [en]", "gcr"],
  ["Chewa [en]", "ny"],
  ["Sotho", "st"],
  ["Cherokee", "chr"],
  ["Kusaal [en]", "kus"],
  ["Swazi", "ss"],
  ["Ewe [en]", "ee"],
  ["Farefare [en] (Gurene)", "gur"],
  ["Tsonga", "ts"],
  ["Gothic", "got"],
  ["Bambara", "bm"],
  ["Norfuk", "pih"],
  ["Toba Batak [en]", "bbc"],
  ["Venda", "ve"],
  ["Romani (Vlax Romani [en])", "rmy"],
  ["Cheyenne [en]", "chy"],
  ["Fante [en]", "fat"],
  ["Kirundi [en]", "rn"],
  ["Igala [en]", "igl"],
  ["Iñupiaq", "ik"],
  ["Wayuu [en]", "guc"],
  ["Adyghe", "ady"],
  ["Chamorro", "ch"],
  ["Pontic Greek [en]", "pnt"],
  ["Inuktitut", "iu"],
  ["Paiwan [en]", "pwn"],
  ["Dinka [en]", "din"],
  ["Sango [en]", "sg"],
  ["Tigrinya", "ti"],
  ["Dzongkha", "dz"],
  ["Greenlandic", "kl"],
  ["West Coast Bajau", "bdr"],
  ["Cree", "cr"],
  ["Lower Sorbian", "dsb"]
]);
